print("Welcome to the Group Name Generator.")
print("What are your favourite colours? ")
colour = input()
print("What is your favourite animal or animals?")
print("nice")
group = input()
print(f"Your group name could be {colour} {group}s")
