print("Welcome to the Group Name Generator.")
print("What is your favourite colour? ")
colour = input()
print("What is your favourite animal or animals?")
group1 = input()
print(f"Your group name could be {colour} {group1}s")
